######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 13 12:55:21 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += filechooser.h mainwindow.h pieview.h
SOURCES += filechooser.cpp main.cpp mainwindow.cpp paint.cpp pieview.cpp
RESOURCES += chart.qrc
