######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 8 05:17:54 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += graph_window.h line.h point.h
SOURCES += graph_window.cpp line.cpp main.cpp point.cpp
