######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 19 19:29:51 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h pieview.h
SOURCES += main.cpp mainwindow.cpp pieview.cpp
RESOURCES += chart.qrc
