#ifndef TIMELINE_PARAMS_H
#define TIMELINE_PARAMS_H

#define DEFAULT_HEIGHT 300
#define DEFAULT_WIDTH 600

#define BRANCH_SEPARATION 40.0
#define MARGIN 20.0

#define TOP_TO_BOTTOM 1
#define BOTTOM_TO_TOP 2

#define TREE_WIDTH_DIRECTION TOP_TO_BOTTOM

#endif
