######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 11 18:14:18 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += axis.h line.h params.h point.h tick.h window.h
SOURCES += axis.cpp line.cpp main.cpp point.cpp tick.cpp window.cpp
